package com.multiple.questions.entities;
// Generated May 15, 2017 9:46:06 PM by Hibernate Tools 5.2.1.Final

/**
 * Userinfo generated by hbm2java
 */
public class Userinfo implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String password;
	private String phone;
	private String address;

	public Userinfo() {
	}

	public Userinfo(String userName, String password, String phone, String address) {
		this.userName = userName;
		this.password = password;
		this.phone = phone;
		this.address = address;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
