package com.multiple.questions.entities;
// Generated May 22, 2017 4:11:25 PM by Hibernate Tools 5.2.1.Final

/**
 * Userinfosecurity generated by hbm2java
 */
public class Userinfosecurity implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String role;
	private String fullName;
	private String country;
	private int enabled;

	public Userinfosecurity() {
	}

	public Userinfosecurity(String username, String password, String role, String fullName, String country,
			int enabled) {
		this.username = username;
		this.password = password;
		this.role = role;
		this.fullName = fullName;
		this.country = country;
		this.enabled = enabled;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public int getEnabled() {
		return this.enabled;
	}

	public void setEnabled(int enabled) {
		this.enabled = enabled;
	}

}
